version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    target-branch: "develop"
